import { Inter } from 'next/font/google'
import './globals.css'
import Navbarr from '@/components/navbarr'
import { Providers } from './providers'

// import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Recipe Cost Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
      <html lang="en" className='dark'  >
      <body className={inter.className}>
        <Providers>
        <div className='max-w-3xl mx-auto p-4'>
          <Navbarr></Navbarr>
        <div className='mt-4'>
          {children}
          </div>
        </div>
        </Providers>
        </body>
    </html>
   
  )
}
